import { defineField, defineType } from 'sanity';
import { HomeIcon } from '@sanity/icons';

export default defineType({
  name: 'pageHome',
  title: '🏠 Home Page',
  type: 'document',
  icon: HomeIcon,
  // Prevent creating more than one — this is a singleton
  // @ts-expect-error - __experimental_actions is used for legacy Sanity singleton behavior
  __experimental_actions: ['update', 'publish'],
  groups: [
    { name: 'hero',     title: '① Hero Section' },
    { name: 'subhero',  title: '② Stats Banner' },
    { name: 'services', title: '③ Explore Services' },
    { name: 'steps',    title: '④ How It Works' },
    { name: 'about',    title: '⑤ About Section' },
    { name: 'contact',  title: '⑥ Contact Info' },
  ],
  fields: [
    // ── HERO ──────────────────────────────────────────────────────────────────
    defineField({
      name: 'heroHeadingLine1',
      title: 'Hero — Heading Line 1',
      type: 'string',
      group: 'hero',
      description: 'First line of the big hero text (e.g. "Professional")',
      initialValue: 'Professional',
    }),
    defineField({
      name: 'heroHeadingLine2',
      title: 'Hero — Heading Line 2',
      type: 'string',
      group: 'hero',
      description: 'Second line of the big hero text (e.g. "Services")',
      initialValue: 'Services',
    }),
    defineField({
      name: 'heroSubheading',
      title: 'Hero — Subheading',
      type: 'string',
      group: 'hero',
      description: 'The smaller tagline text shown below the main heading',
      initialValue: 'UAE\'s #1 Technical Services — AC · Plumbing · Painting · Maintenance',
    }),
    defineField({
      name: 'heroBadgeText',
      title: 'Hero — Trust Badge Text (left)',
      type: 'string',
      group: 'hero',
      description: 'Short text left of the stars (e.g. "Excellent")',
      initialValue: 'Excellent',
    }),
    defineField({
      name: 'heroTrustpilotText',
      title: 'Hero — Trustpilot Label (right of stars)',
      type: 'string',
      group: 'hero',
      description: 'Text right of stars (e.g. "5000+ Reviews · Trustpilot")',
      initialValue: '5000+ Reviews · Trustpilot',
    }),
    defineField({
      name: 'heroPrimaryButtonText',
      title: 'Hero — Primary Button Text',
      type: 'string',
      group: 'hero',
      initialValue: '🚀 Get FREE Quote',
    }),
    defineField({
      name: 'heroSecondaryButtonText',
      title: 'Hero — Secondary Button Text',
      type: 'string',
      group: 'hero',
      initialValue: '📞 Call Now',
    }),
    defineField({
      name: 'heroDescriptionText',
      title: 'Hero — Description Paragraph (below video)',
      type: 'text',
      group: 'hero',
      description: 'The paragraph shown in the grey band below the video',
      initialValue: 'We deliver seamless, user-friendly, and simple booking for all your home maintenance needs across the UAE.',
    }),
    defineField({
      name: 'heroVideo',
      title: 'Hero — Background Video',
      type: 'file',
      group: 'hero',
      options: { accept: 'video/*' },
      description: 'Upload an MP4 video for the hero background. If empty, the default video is used.',
    }),

    // ── STATS BANNER ─────────────────────────────────────────────────────────
    defineField({
      name: 'stat1Title',
      title: 'Stats — Card 1 Title',
      type: 'string',
      group: 'subhero',
      description: 'e.g. "50+ Services"',
      initialValue: '50+ Services',
    }),
    defineField({
      name: 'stat1Description',
      title: 'Stats — Card 1 Description',
      type: 'text',
      group: 'subhero',
      initialValue: 'From AC maintenance to full property renovation — we cover every technical need across the UAE.',
    }),
    defineField({
      name: 'stat2Title',
      title: 'Stats — Card 2 Title',
      type: 'string',
      group: 'subhero',
      description: 'e.g. "200+ Providers"',
      initialValue: '200+ Providers',
    }),
    defineField({
      name: 'stat2Description',
      title: 'Stats — Card 2 Description',
      type: 'text',
      group: 'subhero',
      initialValue: 'A vetted network of certified technicians ready to serve you with guaranteed quality workmanship.',
    }),
    defineField({
      name: 'stat3Title',
      title: 'Stats — Card 3 Title',
      type: 'string',
      group: 'subhero',
      description: 'e.g. "5000+ Customers"',
      initialValue: '5000+ Customers',
    }),
    defineField({
      name: 'stat3Description',
      title: 'Stats — Card 3 Description',
      type: 'text',
      group: 'subhero',
      initialValue: 'Thousands of satisfied homeowners and businesses across Dubai and UAE have trusted Aqsa Tech.',
    }),

    // ── EXPLORE SERVICES ─────────────────────────────────────────────────────
    defineField({
      name: 'exploreTitle',
      title: 'Explore Services — Section Title',
      type: 'string',
      group: 'services',
      initialValue: 'Explore Our Services',
    }),
    defineField({
      name: 'exploreSubtitle',
      title: 'Explore Services — Subtitle',
      type: 'string',
      group: 'services',
      initialValue: 'Find the right service for your home or business',
    }),
    defineField({
      name: 'buildingMaintenanceImage',
      title: 'Explore — Building Maintenance Image',
      type: 'image',
      group: 'services',
      options: { hotspot: true },
      description: 'Image shown in the Building Maintenance tab',
    }),
    defineField({
      name: 'propertyMaintenanceImage',
      title: 'Explore — Property Maintenance Image',
      type: 'image',
      group: 'services',
      options: { hotspot: true },
    }),
    defineField({
      name: 'renovationImage',
      title: 'Explore — Renovation Image',
      type: 'image',
      group: 'services',
      options: { hotspot: true },
    }),
    defineField({
      name: 'mepImage',
      title: 'Explore — MEP Services Image',
      type: 'image',
      group: 'services',
      options: { hotspot: true },
    }),
    defineField({
      name: 'hvacImage',
      title: 'Explore — HVAC Image',
      type: 'image',
      group: 'services',
      options: { hotspot: true },
    }),
    defineField({
      name: 'paintingImage',
      title: 'Explore — Painting Image',
      type: 'image',
      group: 'services',
      options: { hotspot: true },
    }),

    // ── HOW IT WORKS ─────────────────────────────────────────────────────────
    defineField({
      name: 'stepsTitle',
      title: 'How It Works — Section Title',
      type: 'string',
      group: 'steps',
      initialValue: 'How does it work?',
    }),
    defineField({
      name: 'stepsSubtitle',
      title: 'How It Works — Subtitle',
      type: 'string',
      group: 'steps',
      initialValue: 'Book your service in 3 easy steps',
    }),
    defineField({
      name: 'step1Title',
      title: 'Step 1 — Title',
      type: 'string',
      group: 'steps',
      initialValue: 'Browse & Choose',
    }),
    defineField({
      name: 'step1Description',
      title: 'Step 1 — Description',
      type: 'text',
      group: 'steps',
      initialValue: 'Browse our full range of professional services and select what best suits your needs.',
    }),
    defineField({
      name: 'step2Title',
      title: 'Step 2 — Title',
      type: 'string',
      group: 'steps',
      initialValue: 'Book & Confirm',
    }),
    defineField({
      name: 'step2Description',
      title: 'Step 2 — Description',
      type: 'text',
      group: 'steps',
      initialValue: 'Contact us via WhatsApp, call, or the contact form. We confirm your slot and send a qualified technician.',
    }),
    defineField({
      name: 'step3Title',
      title: 'Step 3 — Title',
      type: 'string',
      group: 'steps',
      initialValue: 'Service Delivered',
    }),
    defineField({
      name: 'step3Description',
      title: 'Step 3 — Description',
      type: 'text',
      group: 'steps',
      initialValue: 'Our certified team arrives on time, completes the work to the highest standard, and ensures your satisfaction.',
    }),

    // ── ABOUT ────────────────────────────────────────────────────────────────
    defineField({
      name: 'aboutBadgeText',
      title: 'About — Badge Label',
      type: 'string',
      group: 'about',
      description: 'Small pill text above the heading (e.g. "Why Choose Us")',
      initialValue: 'Why Choose Aqsa Tech',
    }),
    defineField({
      name: 'aboutHeading',
      title: 'About — Heading',
      type: 'string',
      group: 'about',
      initialValue: 'Dubai\'s Most Trusted Technical Services Company',
    }),
    defineField({
      name: 'aboutDescription',
      title: 'About — Description',
      type: 'text',
      group: 'about',
      initialValue: 'Since 2020, Aqsa Tech has been delivering premium home and commercial maintenance services across UAE. We combine certified expertise, genuine care, and transparent pricing to give every customer a seamless experience.',
    }),
    defineField({
      name: 'aboutMainImage',
      title: 'About — Main Photo',
      type: 'image',
      group: 'about',
      options: { hotspot: true },
      description: 'Large image on the left side of the About section',
    }),
    defineField({
      name: 'aboutDetailImage',
      title: 'About — Small Detail Photo (corner)',
      type: 'image',
      group: 'about',
      options: { hotspot: true },
      description: 'Small secondary image shown in the bottom corner of the About section',
    }),

    // ── CONTACT ──────────────────────────────────────────────────────────────
    defineField({
      name: 'contactPhone',
      title: 'Contact — Phone Number',
      type: 'string',
      group: 'contact',
      description: 'Primary phone number shown across the site',
      initialValue: '+971 52 501 0132',
    }),
    defineField({
      name: 'contactEmail',
      title: 'Contact — Email Address',
      type: 'string',
      group: 'contact',
      initialValue: 'services@aqsatech.ae',
    }),
    defineField({
      name: 'contactWhatsapp',
      title: 'Contact — WhatsApp Number (digits only)',
      type: 'string',
      group: 'contact',
      description: 'No + or spaces. Used for wa.me links.',
      initialValue: '971525010132',
    }),
    defineField({
      name: 'contactAddress',
      title: 'Contact — Address',
      type: 'string',
      group: 'contact',
      initialValue: 'United Arab Emirates',
    }),
    defineField({
      name: 'contactHours',
      title: 'Contact — Working Hours',
      type: 'string',
      group: 'contact',
      initialValue: 'Mon - Fri: 8AM - 6PM',
    }),
  ],

  preview: {
    select: { title: 'heroHeadingLine1' },
    prepare() {
      return { title: '🏠 Home Page Content', subtitle: 'Click to edit all homepage sections' };
    },
  },
});
